### ISSUE TITLE
Future Roadmap

### ISSUE THREAD

**Issue by vivinjoy** [mohebifar/lebab#69]
Hi. Is there a timeline for when the rest of the ES6 features will be supported ?

**Comment by nene** [comment]
Apparently there's some sort of roadmap in the old [xto6 site](http://xto6.js.org/). It lists the following:

- Convert commonjs module definitions
- Convert var to let/const
- For of loops
- Convert arguments to rest parameters
- Remove `_this=this` for arrow functions

Of these the let/const transform has been implemented, but is quite buggy. Instead of these some other transforms have been implemented:

- Default arguments instead of `a = a || 2`
- Function properties in objects to Object methods
- Object property shorthands

I guess any roadmap should be taken with a good grain of salt.
